### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#1]
Create a SQL script with the database tables that will be used to store information about the users and the businesses / sites offering services.

Rough outline of tables:

**Users**: type (driver,business), username, salted password hash, email address, 2fa details, session info
**Business**: owner foreign key (may be null), address, lat, long, list of services, hours of operation, photo, upvotes,downvotes

Use stored procedures for table insert/update operations.

**Comment by domcho** [comment]
Added a table called "facilities" to represent locations/services.

**Comment by domcho** [comment]
Updated the database to include "diesel" and "other" services

**Comment by iamjillsanluis** [comment]
The functionality is already built by Dom/Tyler/Jeremy. Closing.
