### ISSUE TITLE
As a trucker, I want to find places for services I am interested in

### ISSUE THREAD

**Issue by iamjillsanluis** [truckerswelcome/webapp#10]
Flow:
1. A trucker visits https://www.truckerswelcome.ca/
1. A modal appears that gives the trucker an option to filter the down the locations of services they are interested in
1. Trucker confirms his choice
1. The locations are displayed in the map

**Comment by tyler-reese** [comment]
An initial modal is presented to allow the user to enter search options as well as either use geolocation or a location from the input box.
Clicking on the Search button will kick off the search with the requested parameters.
The locations will be displayed on the map.
Currently, changing the filter options requires a page reload.
