### ISSUE TITLE
As a concerned citizen, I should be able to update/delete existing business information

### ISSUE THREAD

**Issue by iamjillsanluis** [truckerswelcome/webapp#11]
Blocker(s): 
* https://github.com/truckerswelcome/webapp/issues/12

# Update
Example scenario: The facilities no longer provides the service. In this situation, the user may uncheck certain 

1. In the facilities information popup, add an Edit button
1. Clicking Edit takes you to store information page that lets you update the facilities. The form should be pre-populate the details of the business from the same form in the `add business page`
    1. Since the facility is existing, there will be hidden id field in the form that matches the DB ID of the facility
1. After updating the business details, clicking Submit updates the records in the database and updates the facilities as `approval_status = "pending"` to mark that it needs to go through the moderation process.

# Delete
1. Clicking on the Edit store link, the page should have a "Delete" button
1. Clicking on this button marks the location deleted.
    1. You will need to have "active" column in the locations table

# Side effects
1. Do not return locations that have `active = 0` in the map
1. Do not display locations that have `approval_status = "pending"` in the map (should already be happening)

**Comment by domcho** [comment]
Implemented and pushed in a01c532..5bd71da
