### ISSUE TITLE
Change the column `approved` to `approval_status`

### ISSUE THREAD

**Issue by iamjillsanluis** [truckerswelcome/webapp#12]
There are three states of approval which does not fit the current column type. They are:
  - pending - newly submitted/updated facilities
  - approved - facilities that should be displayed
  - rejected - facilities that were submitted but decided to be filtered out from displayable locations

# Task:
1. Add new column `approval_status` with ENUM `pending`, `approved`, `rejected`
1. Backfill the `approval_status="approved"` for locations with `approved = 1`
1. Backfill the `approval_status="pending"` for locations with `approved = 0`

There is only very few facilities now that we don't have to worry about the `rejected` case, but once we have the moderation process in place, this change will streamline that process.

**Comment by domcho** [comment]
Pushed in d5e077d..b2eca36
