### ISSUE TITLE
Add a "Share" button

### ISSUE THREAD

**Issue by iamjillsanluis** [truckerswelcome/webapp#15]
We want to get people to help us seed the app with reliable data. Hopefully, the power of social media can help us.

Add a button in the home page to make it easier for users to share it in their
- [x] Facebook
- [x] Twitter
- [x] LinkedIn

Perhaps, having a blurb too of what the app does when sharing it would help position the messaging better.

Instagram is moved to another ticket - #29 .

**Comment by mkimsy** [comment]
Instagram!
