### ISSUE TITLE
Terms of use of truckerswelcome.ca to ensure we are not selling data to monetize

### ISSUE THREAD

**Issue by mkimsy** [truckerswelcome/webapp#26]
Attached is the light draft, ended up being 10 pages... If we think it's overkill, I can cut more. see below.

**Comment by mkimsy** [comment]
I just realized LinkedIn may be another one - new attached version ignore the one above. 
[Truckerswelcome Terms of Service.docx](https://github.com/truckerswelcome/webapp/files/4459396/Truckerswelcome.Terms.of.Service.docx)

**Comment by iamjillsanluis** [comment]
So pro ❤️ !

**Comment by iamjillsanluis** [comment]
The only problem is it uses `.docx` :trollface: 😄

**Comment by domcho** [comment]
Link to terms has been added to the menu and search results, if you are happy we can close this issue.
