### ISSUE TITLE
Apostrophe not escaped in 'other' facility options

### ISSUE THREAD

**Issue by maxlvl** [truckerswelcome/webapp#36]
**Steps to reproduce:**
1) Add a new facility.
2) Under 'other' facility options, add anything with an apostrophe (e.g. "driver's lounge") 
3) Save the newly added facility and look it up a minute later. 

**Expected result:**
I can see "driver's lounge" among the options

**Actual result:** 
I see "driver&amp;39#;s lounge" among the options.

**Comment by tyler-reese** [comment]
I checked in a fix for this. Try it again and see if it works for you.
