### ISSUE TITLE
Register a business in the app

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#4]
Implement the UI to allow a user to create a new account. Accounts are needed in order to allow a business owner to maintain the entry for their business such as provide contact information, update the services that are offered, remove the business from the application, etc.

When a new user signs up as a business owner, the email address used should be verified as a step to activating the account.

A new user may also be a driver, not sure why a driver would need a profile at this time.

**Comment by iamjillsanluis** [comment]
MVP does not have any notion of user as it is not necessary. However, registration of business is already supported as implemented by Dom/Tyler/Jeremy. 

Closing.
