### ISSUE TITLE
Add a new business / facility

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#5]
Business owners will be able to add information about a business or facility they own & operate. A single owner may have multiple businesses so the relationship in the DB will be one-to-many. A form with all the required fields will be provided that logged in business owners can use to enter all the required information. The address provided by the user will be converted to lat/long prior to updating the database to allow location based searched.

Unregistered users should also be able to add information to the database, e.g. a driver who has found a portable toilet in a parking lot that is available to the public, should be able to snap a pic and add the location + service offered.

**Comment by iamjillsanluis** [comment]
There is no notion of users in the MVP. We cover validation through the manual moderation process. Adding of Business/Facility is already built by Dom/Tyler/Jeremy. Closing.
