### ISSUE TITLE
Failure to save when inputing data with no error to user due to uncaught syntax error

### ISSUE THREAD

**Issue by ahalliop** [truckerswelcome/webapp#50]
Try to add the following info:
Bassano, AB 
Emmeís Esso Truck Stop 
Location: 602 12 St. 
Amenities: Lobby open, washroom, sit-down open

Don't see any errors, but pressing Save button doesn't do anything. It says Blue.

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (tw.js:94)

**Comment by tyler-reese** [comment]
Did you enter a phone number and postal code?

**Comment by ahalliop** [comment]
The issue used to be seen even when I had phone number and postal code.

Retested approx April 18th 1:10pm & it works as expected.
