### ISSUE TITLE
Upvote / downvote a business

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#6]
Drivers will be able to upvote or downvote a business. If they arrive at a location and services match with what is listed in the application they can upvote. If services do not match, they can downvote. 

These upvotes/downvotes will be used to present a score for each business in search results to allow drivers to avoid entries that are not quite what they claim. A facility may also be automatically excluded from search results with sufficient downvotes.

Security mechanisms should be implemented to avoid automated voting.

**Comment by ionut998** [comment]
another ruby gem that can help us with this functionality
https://github.com/ryanto/acts_as_votable

**Comment by iamjillsanluis** [comment]
This is out of scope for MVP. This will be covered post MVP and will be scoped in #18 . Closing for now.
