### ISSUE TITLE
Search for a business

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#7]
Drivers should be able to search for a business or facility providing specific services (e.g. washroom) using either their current location as obtained from the browser, or by entering an address.

Results will be displayed using markers on a Google Map, and in text form in a vertically scrollable frame. The results will include relevant information (address, hours, contact info, vote score) as well as links to allow drivers to contact the business and upvote/downvote it. There will also be a link to allow a driver to report a problem, e.g. business does not really exist, etc.

**Comment by iamjillsanluis** [comment]
This is already implemented. Closing the ticket.
