### ISSUE TITLE
User login / logout

### ISSUE THREAD

**Issue by domcho** [truckerswelcome/webapp#8]
Add form to allow users to log in and log out. A login history should be maintained and users should be shown their last login. Login history should be used to mitigate brute force. 2FA using Google Authenticator should be supported (optional to the user).

**Comment by ionut998** [comment]
It looks like there is a lib that can help us here if we build this on Rails
https://github.com/jaredonline/google-authenticator

**Comment by iamjillsanluis** [comment]
Out of scope for MVP. Closing.
